### PR TITLE
Allow logging to be silenced or intercepted

### PR DESCRIPTION
**Pull request by joelverhagen**

### CODE REVIEW

**Comment by Laiteux** [comment]
👀

**Comment by joelverhagen** [comment]
@Laiteux, yup this is for https://github.com/joelverhagen/TorSharp/issues/89 and https://github.com/joelverhagen/TorSharp/issues/52. The tests are being very flaky right now and I haven't had a chance to figure out why. Coming soon ™️

**Comment by joelverhagen** [comment]
@Laiteux, try out version 2.11.0. I added this sample to help:
https://github.com/joelverhagen/TorSharp/blob/release/samples/CustomLogging/Program.cs

**Comment by Laiteux** [comment]
Thank you, works as expected! (:

**Pull request merged**
