### PR TITLE
Update Process.cs

### PR DESCRIPTION
**Pull request by MahmutYaman**
WinApi usage error.

### CODE REVIEW

**Comment by joelverhagen** [comment]
Could you help me understand the motivation of this change? I reviewed the Windows API docs and it seems like sending null as the first parameter (`lpApplicationName`) is allowed. In such a case the module then Windows kicks off is the first argument, which is expected to be the module path either way.
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa#parameters

Perhaps you are running the tools from a path that has a space in it? There is a strange part of the docs that mention a probing pattern if the module path has spaces. I have an a test for the "spaces in path" case so I was thinking this was okay, but maybe I missed something!

**Comment by MahmutYaman** [comment]
I was have a space in my tools path and the API return an error about file path.

**Comment by joelverhagen** [comment]
Could you provide the full error message? And what your file paths looks like?

With your current changeset it seems Tor is failing to start. I believe this is because most apps expect the module path as the first argument.

I think we just need to put quotes around the path that we pass into the Windows API.

**Comment by MahmutYaman** [comment]
Yeah, its will be fixed with that way too as the docs says.
My path was "C:\Users\Mahmut Yaman\Desktop\Yeni Klasör".
There is a Turkish letter in the path too. "Yeni Klasör" means "New Folder".
I don't know is it a issue but it seems becouse only spaces.
Also I don't remember the error message and I'm not using this library anymore.
I found a better and quick solution for my application.
Its here: https://codeshare.io/5Ov3Kv
Also I'm using a library which is converting socks to http and its here: https://github.com/postworthy/SocksWebProxy/

There is a different algorithm on changing circuits becouse when you ask for a new circuits, Tor don't changing instantly. There is a defination about how often will be honored SIGNEWNYM requests in this source code: https://github.com/torproject/tor/blob/master/src/core/mainloop/mainloop.c#L153

My code is maybe like a spaghetti for now but its very new :)
Just sharing for ideas.

**Comment by joelverhagen** [comment]
The root of the issue seems to be the unicode characters in the path. I have opened an issue to track this: https://github.com/joelverhagen/TorSharp/issues/39.

**Pull request closed without merging**
