### PR TITLE
Bridge creation support

### PR DESCRIPTION
**Pull request by AMBULATUR**
#56 
By the way, if you want to MAKE YOUR OWN bridge instead to connection to other user bridge, please use these settings.

### CODE REVIEW

**Comment by joelverhagen** [comment]
Looks great! Thanks!

@AMBULATUR - just curious, are you planning on using these settings for your own application? I am not familiar with these specific settings and I'm curious about what you're building 😄

**Comment by AMBULATUR** [comment]
So, already using previous sets for connection ThRoUghT obfs4 bridge at my purposes, but i'm currently not planning on using these settings for creation [transport] bridges, but maybe someone wants to make own torify / tor-dev scrapper or something else with transport plugins.
And for note sake's, i think your idea with "Given how specific this is maybe we need a generic property back added to TorSharpTorSettings to allow these properties to be added (something like Dictionary<string, string> where the key is the configuration name and the value is everything after the key). " looks great, and it need a realization.

**Review by joelverhagen — APPROVED** [review]
Having strongly typed properties like this is a nice convenience. We can consider the generic `Dictionary<string, string>` approach if this approach becomes unwieldly. 

Thanks!

**Comment by joelverhagen** [comment]
Released in version 2.4.0. Thanks again, @AMBULATUR!
https://www.nuget.org/packages/Knapcode.TorSharp/2.4.0

**Pull request merged**
