### PR TITLE
Bump .NET Framework to newest supported TFM

### LINKED ISSUE #76: Bump .NET Framework to newest supported TFM
.NET45 has been out of support for a while now. Bump to .net472 which is the latest & greatest.

### PR DESCRIPTION
**Pull request by kzu**
Fixes #76

### CODE REVIEW

**Comment by joelverhagen** [comment]
What's the benefit of this? Is a new API available that is needed?

I don't have any data on how the project is used so it's hard to tell if this will break people.

I'm okay with this change but I think there should be a small victory from this change to warrant it.

**Comment by kzu** [comment]
OOB compatibility with NS2.0 libraries for one :). You can search the web for the clusterf###k it is to develop targeting net45 while consuming NS2 libraries since a sh** ton of otherwise unnecessary nuget package dependencies need to be restored for it to work. 

For one thing, shipping *new* package versions supporting unsupported .NET framework seems a bit pointless, I might say: https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework. Support for .net45 ended full 5 years ago. And .net472 is supported from Win7+.

FWIW, you wouldn't be breaking anyone who's *not* updating. They can still use the previous version if they run in such an ancient platform.

**Comment by kzu** [comment]
See for example https://github.com/dotnet/sdk/issues/1630 (and that's against net461, I doubt you'll even find anything related to net45 these days...)

**Comment by kzu** [comment]
More on the super broad support net472 has today: https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-7-2/

**Comment by joelverhagen** [comment]
I wonder if the unnecessary dependency problem could be mitigated by adding the `net472` target additionally to `net45`. Could that be the best of both worlds?

**Comment by kzu** [comment]
Yep, that's doable too :). I can update the PR

**Comment by joelverhagen** [comment]
Awesome, thanks @kzu! I'll work on getting a release out.

**Pull request merged**
