### PR TITLE
fix: updated Tor tool path and format after Tor 12.0 changed everything

### PR DESCRIPTION
**Pull request by ZimM-LostPolygon**
Seems like Tor 12.0 changed some things around how the releases are packaged. This PR updates the tool fetcher to match that. Some notes:
- `System.IO.GZipStream` seems to be available for .NET 4.5, however I wasn't able to verify that, so I kept the .tar.gz format support at .NET Standard only...
- I'm not sure why the Tor Browser was used for Linux before, but perhaps we can use the "tor-expert-bundle" release format for Linux as well?
- I've only tested on Windows x64 and Linux x64, however x86 should work just as fine.

### CODE REVIEW

**Comment by ZimM-LostPolygon** [comment]
This also fixes https://github.com/joelverhagen/TorSharp/issues/91

**Comment by joelverhagen** [comment]
This looks great, @ZimM-LostPolygon. Thanks for taking the time to do this. I'm going to take a look at it today and hopefully get out a fixed release soon.

**Comment by joelverhagen** [comment]
> - `System.IO.GZipStream` seems to be available for .NET 4.5, however I wasn't able to verify that, so I kept the .tar.gz format support at .NET Standard only...

I've changed the approach to use SharpCompress everywhere. This should make things simpler and easily cross-platform.

> I'm not sure why the Tor Browser was used for Linux before, but perhaps we can use the "tor-expert-bundle" release format for Linux as well?

It was not available previously. See: https://tor.stackexchange.com/questions/20147/why-is-there-no-stand-alone-tor-binaries-for-os-x-and-linux-on-dist. I'll try to switch to the expert bundle since it is much smaller.

> I've only tested on Windows x64 and Linux x64, however x86 should work just as fine.

I'll test it.

**Comment by ZimM-LostPolygon** [comment]
> I've changed the approach to use SharpCompress everywhere. This should make things simpler and easily cross-platform.

That was my idea as well, however, trying it out, I was getting some weird exceptions from deep inside SharpCompress's GZipStream implementation. Maybe it was a fluke, maybe it wasn't, but switching to `System.IO.GZipStream` fixed the issue for me, plus `System.IO.GZipStream` probably has a native implementation, so it's going to be a bit faster... Not that it matters much.

**Comment by joelverhagen** [comment]
Yikes, I hope we can get to the bottom of those weird exceptions if they recur. I'll proceed for now with using SharpCompress everywhere and see what happens on the GitHub Actions test matrix (lots of OSs). What platform had this problem?

**Comment by ZimM-LostPolygon** [comment]
I had it Windows x64 at least, didn't check anywhere else. I haven't noted down any exception stacktraces or anything else, unfortunately.

**Comment by joelverhagen** [comment]
Thanks for kicking this off @ZimM-LostPolygon! I'll work on getting a release out.

**Pull request merged**
